PatrimoineBundle\Entity\Association:
    type: entity
    table: null
    repositoryClass: PatrimoineBundle\Repository\AssociationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre1:
            type: string
            length: 255
        titre2:
            type: string
            length: 255
        titre3:
            type: string
            length: 255
        titre4:
            type: string
            length: 255
        article1:
            type: string
            length: 255
        article2:
            type: string
            length: 255
        article3:
            type: string
            length: 255
        article4:
            type: string
            length: 255
    lifecycleCallbacks: {  }
