PatrimoineBundle\Entity\Histoire:
    type: entity
    table: null
    repositoryClass: PatrimoineBundle\Repository\HistoireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        article1:
            type: string
            length: 255
        article2:
            type: string
            length: 255
    lifecycleCallbacks: {  }
