PatrimoineBundle\Entity\Mecene:
    type: entity
    table: null
    repositoryClass: PatrimoineBundle\Repository\MeceneRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        presentation:
            type: string
            length: 255
        formulaire1:
            type: string
            length: 255
        formulaire2:
            type: string
            length: 255
    lifecycleCallbacks: {  }
