PatrimoineBundle\Entity\Realisation:
    type: entity
    table: null
    repositoryClass: PatrimoineBundle\Repository\RealisationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre1:
            type: string
            length: 255
        article1:
            type: string
            length: 255
        titre2:
            type: string
            length: 255
        article2:
            type: string
            length: 255
        titre3:
            type: string
            length: 255
        article3:
            type: string
            length: 255
        titre4:
            type: string
            length: 255
        article4:
            type: string
            length: 255
        titre5:
            type: string
            length: 255
        article5:
            type: string
            length: 255
        titre6:
            type: string
            length: 255
        article6:
            type: string
            length: 255
        titre7:
            type: string
            length: 255
        article7:
            type: string
            length: 255
        titre8:
            type: string
            length: 255
        article8:
            type: string
            length: 255
        titre9:
            type: string
            length: 255
        article9:
            type: string
            length: 255
        titre10:
            type: string
            length: 255
        article10:
            type: string
            length: 255
    lifecycleCallbacks: {  }
