PatrimoineBundle\Entity\Realisation:
    type: entity
    table: null
    repositoryClass: PatrimoineBundle\Repository\RealisationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre1:
            type: string
            length: 255
            nullable: TRUE
        article1:
            type: text
            nullable: TRUE
        image1:
            type: string
            nullable: TRUE

        titre2:
            type: string
            length: 255
            nullable: TRUE
        article2:
            type: text
            nullable: TRUE
        image2:
            type: string
            nullable: TRUE

        titre3:
            type: string
            length: 255
            nullable: TRUE
        article3:
            type: text
            nullable: TRUE
        image3:
            type: string
            nullable: TRUE

        titre4:
            type: string
            length: 255
            nullable: TRUE
        article4:
            type: text
            nullable: TRUE
        image4:
            type: string
            nullable: TRUE

        titre5:
            type: string
            length: 255
            nullable: TRUE
        article5:
            type: text
            nullable: TRUE
        image5:
            type: string
            nullable: TRUE

        titre6:
            type: string
            length: 255
            nullable: TRUE
        article6:
            type: text
            nullable: TRUE
        image6:
            type: string
            nullable: TRUE

        titre7:
            type: string
            length: 255
            nullable: TRUE
        article7:
            type: text
            nullable: TRUE
        image7:
            type: string
            nullable: TRUE

        titre8:
            type: string
            length: 255
            nullable: TRUE
        article8:
            type: text
            nullable: TRUE
        image8:
            type: string
            nullable: TRUE

        titre9:
            type: string
            length: 255
            nullable: TRUE
        article9:
            type: text
            nullable: TRUE
        image9:
            type: string
            nullable: TRUE

        titre10:
            type: string
            length: 255
            nullable: TRUE
        article10:
            type: text
            nullable: TRUE
        image10:
            type: string
            nullable: TRUE


    lifecycleCallbacks:
      prePersist: [ preUpload, preUpload2, preUpload3,preUpload4, preUpload5, preUpload6, preUpload7, preUpload8, preUpload9, preUpload10 ]
      preUpdate: [ preUpload, preUpload2, preUpload3,preUpload4, preUpload5, preUpload6, preUpload7, preUpload8, preUpload9, preUpload10 ]
      postPersist: [ upload, upload2, upload3, upload4, upload5, upload6, upload7, upload8, upload9, upload10 ]
      postUpdate: [ upload, upload2, upload3, upload4, upload5, upload6, upload7, upload8, upload9, upload10 ]
      postRemove: [ removeUpload, removeUpload2, removeUpload3, removeUpload4, removeUpload5, removeUpload6, removeUpload7, removeUpload8, removeUpload9, removeUpload10 ]
