PatrimoineBundle\Entity\Realisation:
    type: entity
    table: null
    repositoryClass: PatrimoineBundle\Repository\RealisationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre1:
            type: string
            length: 255
            nullable: TRUE
        article1:
            type: text
            nullable: TRUE
        titre2:
            type: string
            length: 255
            nullable: TRUE
        article2:
            type: text
            nullable: TRUE
        titre3:
            type: string
            length: 255
            nullable: TRUE
        article3:
            type: text
            nullable: TRUE
        titre4:
            type: string
            length: 255
            nullable: TRUE
        article4:
            type: text
            nullable: TRUE
        titre5:
            type: string
            length: 255
            nullable: TRUE
        article5:
            type: text
            nullable: TRUE
        titre6:
            type: string
            length: 255
            nullable: TRUE
        article6:
            type: text
            nullable: TRUE
        titre7:
            type: string
            length: 255
            nullable: TRUE
        article7:
            type: text
            nullable: TRUE
        titre8:
            type: string
            length: 255
            nullable: TRUE
        article8:
            type: text
            nullable: TRUE
        titre9:
            type: string
            length: 255
            nullable: TRUE
        article9:
            type: text
            nullable: TRUE
        titre10:
            type: string
            length: 255
            nullable: TRUE
        article10:
            type: text
            nullable: TRUE
        image:
            type: string
            length: 255

    lifecycleCallbacks:
      prePersist: [ preUpload ]
      preUpdate: [ preUpload ]
      postPersist: [ upload ]
      postUpdate: [ upload ]
      postRemove: [ removeUpload ]
