# src/AppBundle/Resources/config/doctrine/User.orm.yml
PatrimoineBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO