association_index:
    path:     /
    defaults: { _controller: "PatrimoineBundle:Association:index" }
    methods:  GET

association_new:
    path:     /new
    defaults: { _controller: "PatrimoineBundle:Association:new" }
    methods:  [GET, POST]

association_edit:
    path:     /{id}/edit
    defaults: { _controller: "PatrimoineBundle:Association:edit" }
    methods:  [GET, POST]

association_delete:
    path:     /{id}/delete
    defaults: { _controller: "PatrimoineBundle:Association:delete" }
    methods:  DELETE
