histoire_index:
    path:     /
    defaults: { _controller: "PatrimoineBundle:Histoire:index" }
    methods:  GET

histoire_show:
    path:     /{id}/show
    defaults: { _controller: "PatrimoineBundle:Histoire:show" }
    methods:  GET

histoire_new:
    path:     /new
    defaults: { _controller: "PatrimoineBundle:Histoire:new" }
    methods:  [GET, POST]

histoire_edit:
    path:     /{id}/edit
    defaults: { _controller: "PatrimoineBundle:Histoire:edit" }
    methods:  [GET, POST]

histoire_delete:
    path:     /{id}/delete
    defaults: { _controller: "PatrimoineBundle:Histoire:delete" }
    methods:  DELETE
