patrimoine_index:
    path:     /
    defaults: { _controller: "PatrimoineBundle:Patrimoine:index" }
    methods:  GET

patrimoine_new:
    path:     /new
    defaults: { _controller: "PatrimoineBundle:Patrimoine:new" }
    methods:  [GET, POST]

patrimoine_edit:
    path:     /{id}/edit
    defaults: { _controller: "PatrimoineBundle:Patrimoine:edit" }
    methods:  [GET, POST]

patrimoine_delete:
    path:     /{id}/delete
    defaults: { _controller: "PatrimoineBundle:Patrimoine:delete" }
    methods:  DELETE
