patrimoine_index:
    path:     /
    defaults: { _controller: "PatrimoineBundle:patrimoine:index" }
    methods:  GET

patrimoine_show:
    path:     /{id}/show
    defaults: { _controller: "PatrimoineBundle:patrimoine:show" }
    methods:  GET

patrimoine_new:
    path:     /new
    defaults: { _controller: "PatrimoineBundle:patrimoine:new" }
    methods:  [GET, POST]

patrimoine_edit:
    path:     /{id}/edit
    defaults: { _controller: "PatrimoineBundle:patrimoine:edit" }
    methods:  [GET, POST]

patrimoine_delete:
    path:     /{id}/delete
    defaults: { _controller: "PatrimoineBundle:patrimoine:delete" }
    methods:  DELETE

patrimoine_realisation:
    path:     /realisation
    defaults: { _controller: "PatrimoineBundle:patrimoine:realisation" }
    methods:  [GET, POST]
