<?php

namespace PatrimoineBundle\Repository;

/**
 * HistoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoireRepository extends \Doctrine\ORM\EntityRepository
{
}
