<?php

namespace PatrimoineBundle\Repository;

/**
 * MeceneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeceneRepository extends \Doctrine\ORM\EntityRepository
{
}
