<?php

namespace PatrimoineBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * patrimoineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class patrimoineRepository extends EntityRepository
{
}
