patrimoine_patrimoine:
    resource: "@PatrimoineBundle/Resources/config/routing/patrimoine.yml"
    prefix:   /patrimoine



patrimoine_homepage:
    path:     /
    defaults: { _controller: PatrimoineBundle:Default:index }


patrimoine_realisation:
    resource: "@PatrimoineBundle/Resources/config/routing/realisation.yml"
    prefix:   /realisation
